#Servre & Tomcat Configration
server:
  port: 9090
#JWT configs
token:
  secret: dcyvrvbusidhAEVvw734683254@@@khv
  time: 24h
#Spring Boot Configration
spring:
#Spring Security Configration
  security:
    user:
      name: ziad
      password: ziad123
  application:
   name: spring-boot-demo
#Oracle Database Configuration
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: hr
    password: hr
#JPA and Hibernate Configuration for Oracle
  jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
#Redis Configuration
#  data:
#    redis:
#      host: localhost
#      port: 49153
#      username: default
#      password: your_redis_password

#Messages Configuration
  messages:
    basename: i18n/messages